#!/usr/bin/env python3
"""norms.py — checks whatever about the norms is mechanically checkable.

    python3 tools/norms.py                  # every check, over the whole tree
    python3 tools/norms.py --commit-msg F   # only the commit message in file F
                                            # (for a commit-msg hook)

**A norm without a checker rots quietly** — same as the domain rule and the evidence
duty. The checker is the reason the structure still holds in four weeks
(prompts/init.md §10).

Every check in here has a section in docs/conventions.md. Change a norm and you change
both.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EXCLUDED = {".git", "target", "saves", "assets/extern", ".cargo", "__pycache__",
            "tools/__pycache__"}


def is_excluded(p: Path) -> bool:
    rel = p.relative_to(ROOT).as_posix()
    parts = set(rel.split("/"))
    return any(rel == a or rel.startswith(a + "/") or a in parts for a in EXCLUDED)


def is_generated(text: str) -> bool:
    """Generated files name their generator in the header and are not maintained."""
    return "GENERATED by tools/" in text[:400]


def files(*patterns: str) -> list[Path]:
    hits: list[Path] = []
    for m in patterns:
        hits += [p for p in ROOT.glob(m) if p.is_file() and not is_excluded(p)]
    return sorted(set(hits))


class Report:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.checked = 0

    def check(self, condition: bool, message: str) -> None:
        self.checked += 1
        if not condition:
            self.errors.append(message)

    def fail(self, message: str) -> None:
        self.errors.append(message)


# --------------------------------------------------------------------------
# 1. Commit message
# --------------------------------------------------------------------------

SUBJECT = re.compile(
    r"^(?:(?:F|T)-\d{3}[a-z]?(?: [a-z]+)?|docs|test|tool|fix|chore): \S.*$")
# `CLAUDE.md` is a file name in this repo and has to be allowed in a message —
# `(?!\.md)` keeps exactly that case out. What is meant is the TOOL NAME, not the file.
TRACES = re.compile(
    r"co-authored-by|generated with|generated by|\bclaude\b(?!\.md)|\bai\b|🤖",
    re.IGNORECASE)


def check_commit_message(text: str, b: Report) -> None:
    lines = text.strip().splitlines()
    if not lines:
        b.fail("commit message is empty")
        return
    subject = lines[0]

    b.check(len(subject) <= 72,
            f"subject is {len(subject)} characters, 72 are allowed: {subject!r}")
    b.check(SUBJECT.match(subject) is not None,
            f"subject does not match '<F-ID|T-ID|docs|test|tool|fix|chore>: <text>': "
            f"{subject!r}")
    b.check(not subject.endswith("."), f"subject ends with a period: {subject!r}")
    b.check(not re.search(r"[\U0001F300-\U0001FAFF☀-➿]", subject),
            f"emoji in the subject (stage marks belong in the body): {subject!r}")

    # No tool or author traces — in the WHOLE text, not just the subject (§10)
    for no, line in enumerate(lines, 1):
        if TRACES.search(line):
            b.fail(f"tool/author trace on line {no}: {line!r} — a commit message "
                   f"describes the change, not its author")
    if len(lines) > 1:
        b.check(lines[1].strip() == "",
                "a blank line belongs between subject and body")


# --------------------------------------------------------------------------
# 2. Terms: no reference term in the code
# --------------------------------------------------------------------------

# Sheet 10_Namensschema is binding. What stands here is a mistake that a grep has to
# find (prompts/init.md §2). `nacken` is the German half of the nape pair: it costs
# nothing to keep and it is the only thing that would catch a relapse into German.
FORBIDDEN = {
    r"\bnape\b": "Cortex",
    r"\bnacken\b": "Cortex",
    r"\bodm\b": "Vector Gear / vector",
    r"\b3dmg\b": "Vector Gear / vector",
    r"\bscouts?\b": "Vanguard",
    r"\bthunder[_ ]?spear\b": "Lance Charge",
    r"\bshifter\b": "Vessel Form",
    r"\btitan[_ ]shifting\b": "Bonding",
    r"\bperk\b": "Trait",
    r"\bartifact\b": "Relic",
    r"\bprestige\b": "Ascension",
    r"\bgems?\b": "Sigil",
    r"\bstuds?\b": "Meter (1 stud = 0.28 m, converted when it goes into the RON)",
    r"\bpure[_ ]titan\b": "Husk",
    r"\babnormal\b": "Errant",
    r"\bcrawler\b": "Scuttler",
    r"\bducker\b": "Weaver",
}

# Files that EXPLAIN the mapping and therefore have to contain the terms.
TERM_EXEMPTIONS = {
    "tools/norms.py",
    "tools/features.py",   # mirrors the COLUMN NAMES of the .xlsx (size_studs)
    "docs/conventions.md",
    "docs/architecture.md",
    "docs/backlog/naming.ron",
    "docs/backlog/gameplay.ron",
    "docs/backlog/tech.ron",
    "docs/backlog/maps.ron",
    "docs/backlog/models.ron",
    "docs/backlog/animations.ron",
    "docs/backlog/audio.ron",
    "docs/backlog/ui.ron",
    "docs/backlog/vfx.ron",
    "docs/backlog/textures.ron",
    "docs/features.ron",
    "docs/FINDINGS.md",
    "docs/QUESTIONS.md",
    "docs/ROADMAP.md",
    "docs/multiplayer.md",
}


def check_terms(b: Report) -> None:
    for p in files("src/**/*.rs", "assets/data/**/*.ron", "tools/**/*.py",
                   "tools/**/*.sh", "scripts/**/*.txt"):
        rel = p.relative_to(ROOT).as_posix()
        if rel in TERM_EXEMPTIONS:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        comment = "//" if p.suffix in (".rs", ".ron") else "#"
        for no, line in enumerate(text.splitlines(), 1):
            # A comment may NAME the reference term — that is exactly where it says why
            # the term no longer appears here and how it converts. It is forbidden in
            # the code and in the data, not in the reasoning.
            code = line.split(comment)[0]
            for pattern, instead in FORBIDDEN.items():
                if re.search(pattern, code, re.IGNORECASE):
                    b.fail(f"{rel}:{no} reference term {pattern} — should be: {instead}")
        b.checked += 1


# --------------------------------------------------------------------------
# 3. Code rules that would rot quietly
# --------------------------------------------------------------------------

def check_code(b: Report) -> None:
    for p in files("src/**/*.rs"):
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        for no, line in enumerate(text.splitlines(), 1):
            code = line.split("//")[0]
            if "unsafe" in code:
                b.fail(f"{rel}:{no} `unsafe` is forbidden — take it to "
                       f"docs/QUESTIONS.md (§9d)")
            if "TEMP" in line:
                b.fail(f"{rel}:{no} forgotten `// TEMP` hack (§15)")
            # No file name in the code: the registry decides which asset is used — there
            # is ONE place that reads it, and that is src/data/ (§7).
            if not rel.startswith("src/data/"):
                if re.search(r'\.load\(\s*"', code):
                    b.fail(f"{rel}:{no} file name in code — the code asks for the "
                           f"logical name, the registry decides (§7)")
                if re.search(r'\b(assets|\.glb|\.ogg|\.png)"', code):
                    b.fail(f"{rel}:{no} asset path in code — belongs in "
                           f"assets/data/art.ron (§7)")
            # §6 rule 3: there is no such thing as 'the player'. Matched on the TYPE and
            # not on the word 'player': a noun turns up in a comment by accident, a
            # `PlayerId` does not — and a check that can no longer fire keeps counting
            # itself as a check while the rule it guards quietly disappears.
            if re.search(r"\.single\(\)|\.single_mut\(\)", code) \
                    and re.search(r"\bPlayerId\b", text):
                b.fail(f"{rel}:{no} `.single()` in a file that knows PlayerId — "
                       f"every player is one of many (§6 rule 3)")
        b.checked += 1


# --------------------------------------------------------------------------
# 4. Docs: ISO date, header line, dead links, orphan files
# --------------------------------------------------------------------------

ISO = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
LINK = re.compile(r"\[[^\]]*\]\(([^)#][^)]*)\)")


def check_docs(b: Report) -> None:
    for p in files("docs/**/*.md", "README.md", "CLAUDE.md"):
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        if not lines:
            b.fail(f"{rel} is empty")
            continue
        if rel not in ("README.md", "CLAUDE.md"):
            b.check(lines[0].startswith("# ") or is_generated(text),
                    f"{rel}: first line is not a heading '# <name> — <one sentence>'")
            # Generated views carry no date of their own: their state is the state of
            # their source, and a date that changes on every run is diff noise.
            if not is_generated(text):
                b.check(any("Updated:" in line for line in lines[:6]),
                        f"{rel}: no 'Updated: <ISO>' line in the first six lines (§10)")
        for no, line in enumerate(lines, 1):
            if line.strip().startswith("Updated:"):
                b.check(ISO.search(line) is not None,
                        f"{rel}:{no} Updated without an ISO date: {line.strip()!r}")
        # dead links
        for target in LINK.findall(text):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            path = (p.parent / target.split("#")[0]).resolve()
            if not path.exists():
                b.fail(f"{rel}: dead link to {target} (§10 — a link into nothing "
                       f"is a bug)")
        b.checked += 1


# An **asset pack** is referenced as a SET and never file by file: `art.ron` names the one
# model it wants, the loader names none at all, and the README describes the naming scheme —
# nobody writes down 278 file names, and nobody should. The per-file mention rule below
# therefore does not apply inside a pack; `check_asset_packs` takes over there with the checks
# that still have teeth.
#
# Measured 2026-08-18, the day the model pack landed: the mention rule produced **316
# violations**, every single one a healthy file. A check that fires on 316 healthy files
# catches nothing — it only teaches you to skip the output, and the next real orphan goes with
# it.
#
# Key: the directory, relative to the repository root. Value: what a file **directly** in it is
# allowed to be called. A directory that does not exist is skipped, an empty one is fine.
ASSET_PACKS = {
    # docs/models.md and assets/3d/glb/README.md: our own work, `<letter>-<nnn>-<what>.glb`.
    "assets/3d/glb": r"^[a-z]-\d{3}-[a-z0-9-]+\.glb$|^README\.md$",
    # The Blender sources beside them, same names.
    "assets/3d/blend": r"^[a-z]-\d{3}-[a-z0-9-]+\.blend$|^README\.md$",
    # assets/texturen/README.md lays the scheme down itself: <TEX-ID>.png is loaded,
    # <TEX-ID>.emissiv.png is the emissive map, <TEX-ID>.felder.ron is the generated field
    # table, index.html is the contact sheet.
    "assets/texturen": (r"^TEX-[A-Z0-9-]+\.png$|^TEX-[A-Z0-9-]+\.emissiv\.png$"
                        r"|^TEX-[A-Z0-9-]+\.felder\.ron$|^README\.md$|^index\.html$"),
    # The hand-kept sources. **The PNG is output** — this is what gets edited.
    "assets/texturen/quelle": r"^TEX-[A-Z0-9-]+\.svg$",
    # Screenshots of the REFERENCE game, not of ours — captured on the Windows machine
    # 2026-08-23 (FIND-149). They are a batch to be looked through, not evidence for one
    # F-ID, so the mention rule would fire once per healthy file. See the folder's README.
    "docs/images/reference-aotr": r"^aotr-[a-z0-9-]+-\d{2}\.png$|^README\.md$",
}

# What a `.glb` may point at from the inside, and where it lands. The models carry
# `../../texturen/TEX-*.png`, which Bevy resolves against the .glb's own folder — so
# `assets/texturen` may never be renamed without every model going untextured, silently.
GLB_MAGIC = b"glTF"


def in_a_pack(rel_dir: str) -> str | None:
    return rel_dir if rel_dir in ASSET_PACKS else None


def check_orphans(b: Report) -> None:
    """Every file is linked and used — or deleted. There is nothing in between.

    **Except inside an asset pack** — see `ASSET_PACKS` and `check_asset_packs`.
    """
    all_texts = []
    for p in files("**/*.md", "**/*.rs", "**/*.ron", "**/*.py", "**/*.sh", "**/*.toml",
                   "**/*.txt"):
        all_texts.append((p, p.read_text(encoding="utf-8", errors="replace")))

    for p in files("docs/**/*", "assets/**/*", "tools/**/*", "scripts/**/*"):
        rel = p.relative_to(ROOT).as_posix()
        if in_a_pack(p.parent.relative_to(ROOT).as_posix()):
            continue
        name = p.name
        mentioned = any(
            (rel in text or name in text) for q, text in all_texts if q != p)
        if not mentioned:
            b.fail(f"{rel} is mentioned nowhere — link it or delete it (§10). "
                   f"A file nobody knows about looks like truth and is never "
                   f"maintained")
        b.checked += 1


# --------------------------------------------------------------------------
# 4b. Asset packs — referenced as a set, checked as a set
# --------------------------------------------------------------------------

def glb_uris(p: Path) -> list[str] | str:
    """Every `uri` a .glb points at from the inside, or a string saying why it cannot be read.

    Only the JSON chunk is read, which stands at the front — the mesh data behind it is not
    touched, so 278 files cost a few hundred kilobytes and not 26 MB.
    """
    import json
    import struct
    try:
        with p.open("rb") as f:
            head = f.read(12)
            if len(head) < 12:
                return "shorter than a glTF header"
            magic, version, declared = struct.unpack("<4sII", head)
            if magic != GLB_MAGIC:
                return f"does not start with {GLB_MAGIC!r} — not a binary glTF"
            if version != 2:
                return f"is glTF version {version}, the loader reads 2"
            if declared != p.stat().st_size:
                return (f"declares {declared} bytes and is {p.stat().st_size} — "
                        f"a truncated file loads as far as it goes and then stops")
            length, kind = struct.unpack("<I4s", f.read(8))
            if kind != b"JSON":
                return f"has {kind!r} where the JSON chunk belongs"
            doc = json.loads(f.read(length))
    except (OSError, ValueError, struct.error) as e:
        return f"cannot be read: {e}"
    out = [i["uri"] for i in doc.get("images", []) if "uri" in i]
    out += [buf["uri"] for buf in doc.get("buffers", []) if "uri" in buf]
    return out


def check_asset_packs(b: Report) -> None:
    """A pack is one thing, so it is checked as one thing.

    What the per-file mention rule used to promise and what stands in its place:

    * **the pack is known**        — the folder itself has to be named somewhere
    * **nothing strays into it**   — every file matches the pack's own naming scheme, so a
                                     `Untitled.blend1`, a leftover `.bin` or a `foo.png`
                                     dropped in by hand is still caught
    * **it holds together inside** — every texture a `.glb` names has to exist where the
                                     model looks for it (this is the check that catches
                                     `assets/texturen` being renamed, which would leave 278
                                     models untextured without a single error)
    * **nothing dangles into it**  — every asset path named in the RON has to exist
    * **the atlas is regrowable**  — every `<TEX>.png` has its `quelle/<TEX>.svg` source and
                                     its `<TEX>.felder.ron` table, because the PNG is output
    """
    all_texts = [(p, p.read_text(encoding="utf-8", errors="replace"))
                 for p in files("**/*.md", "**/*.rs", "**/*.ron", "**/*.py", "**/*.toml")]

    for pack, pattern in ASSET_PACKS.items():
        folder = ROOT / pack
        if not folder.is_dir():
            continue
        name = folder.name
        known = any((pack in text or f"{name}/" in text) for q, text in all_texts
                    if not q.is_relative_to(folder))
        b.check(known, f"{pack}/ is mentioned nowhere — a whole pack nobody links to is "
                       f"318 orphans in one folder (§10)")

        allowed = re.compile(pattern)
        for p in sorted(folder.iterdir()):
            if not p.is_file() or is_excluded(p):
                continue
            b.check(allowed.match(p.name) is not None,
                    f"{pack}/{p.name} does not fit the pack's naming scheme "
                    f"({pattern}) — a stray file in a pack is the one file nobody "
                    f"maintains (§10)")

    # Inside every model: the textures it points at.
    for p in files("assets/3d/glb/*.glb"):
        rel = p.relative_to(ROOT).as_posix()
        uris = glb_uris(p)
        if isinstance(uris, str):
            b.fail(f"{rel} {uris}")
            continue
        for uri in uris:
            if uri.startswith("data:"):
                continue
            target = (p.parent / uri).resolve()
            b.check(target.exists(),
                    f"{rel} points at {uri} and that file is not there — a model whose "
                    f"texture is missing renders white and says nothing")
            b.check(target.is_relative_to(ROOT / "assets"),
                    f"{rel} points at {uri}, which leaves assets/ — the game ships "
                    f"assets/, not the machine it was exported on")

    # Every atlas can be built again from its own source.
    atlas = ROOT / "assets/texturen"
    if atlas.is_dir():
        for png in sorted(atlas.glob("TEX-*.png")):
            if png.name.endswith(".emissiv.png"):
                continue
            tex = png.stem
            b.check((atlas / "quelle" / f"{tex}.svg").is_file(),
                    f"assets/texturen/{png.name} has no quelle/{tex}.svg — the PNG is "
                    f"output, and output without its source cannot be changed")
            b.check((atlas / f"{tex}.felder.ron").is_file(),
                    f"assets/texturen/{png.name} has no {tex}.felder.ron — without the "
                    f"field table nothing can look a field up by name")

    # And the other direction: a path named in the data has to lead somewhere.
    asset_path = re.compile(r'"([^"]*\.(?:glb|png|ogg|wav|ron))"')
    for p in files("assets/data/**/*.ron"):
        rel = p.relative_to(ROOT).as_posix()
        for no, line in enumerate(p.read_text(encoding="utf-8", errors="replace")
                                  .splitlines(), 1):
            for hit in asset_path.findall(line.split("//")[0]):
                b.check((ROOT / "assets" / hit).is_file(),
                        f"{rel}:{no} names {hit} and there is no such file under assets/ "
                        f"— a dangling reference renders a primitive and logs one line")


# --------------------------------------------------------------------------
# 5. Test names and screenshot names
# --------------------------------------------------------------------------

def check_tests(b: Report) -> None:
    fn_name = re.compile(r"^\s*fn\s+([a-z0-9_]+)\s*\(")
    for p in files("tests/**/*.rs"):
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()
        for no, line in enumerate(lines):
            if "#[test]" not in line:
                continue
            for following in lines[no + 1:no + 4]:
                m = fn_name.match(following)
                if not m:
                    continue
                name = m.group(1)
                # A test name states the CLAIM that holds — not 'test_gas'.
                if name.startswith("test_"):
                    b.fail(f"{rel}: test is called {name!r} — the name is the claim "
                           f"that holds (e.g. f014_boost_consumes_gas), not 'test_x'")
                if re.match(r"^[ft]\d{3}", name) and "_" not in name:
                    b.fail(f"{rel}: test {name!r} has an ID but no claim")
                break
        b.checked += 1

    for p in files("docs/images/*"):
        rel = p.relative_to(ROOT).as_posix()
        if p.suffix.lower() != ".png":
            continue
        # `p` alongside f/t/b, and 1..3 digits: the five prerequisites P1..P5 have NO F-ID
        # anywhere in the 245 backlog rows (docs/PLAN-GAME.md §8) — there is no row for "the
        # game has a working mouse" or "UI reaches an offscreen image". Their evidence is
        # still evidence, and a picture that cannot be named cannot be filed.
        if not re.match(r"^[ftbp]-?\d{1,3}[a-z]?-[a-z0-9-]+(-before|-after)?\.png$",
                        p.name):
            b.fail(f"{rel}: screenshot name does not match "
                   f"<f-id>-<short>[-before|-after].png (§10)")
        b.checked += 1


# --------------------------------------------------------------------------

def main() -> int:
    b = Report()

    if "--commit-msg" in sys.argv:
        i = sys.argv.index("--commit-msg")
        path = Path(sys.argv[i + 1])
        check_commit_message(
            path.read_text(encoding="utf-8").split("# ------------------------ >8")[0], b)
    else:
        check_terms(b)
        check_code(b)
        check_docs(b)
        check_orphans(b)
        check_asset_packs(b)
        check_tests(b)

    if b.errors:
        print(f"NORMS: {len(b.errors)} violation/violations "
              f"({b.checked} checks):", file=sys.stderr)
        for e in b.errors:
            print("  - " + e, file=sys.stderr)
        return 1
    print(f"NORMS: clean ({b.checked} checks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
