#!/usr/bin/env python3
"""normen.py — prueft, was an den Normen mechanisch pruefbar ist.

    python3 tools/normen.py                  # alle Pruefungen ueber den Baum
    python3 tools/normen.py --commit-msg F   # nur die Commit-Message in Datei F
                                             # (fuer einen commit-msg-Hook)

**Eine Norm ohne Pruefer verfaellt still** — genau wie die Domaenenregel und die
Belegpflicht. Der Pruefer ist der Grund, dass die Struktur in vier Wochen noch stimmt
(prompts/init.md §10).

Jede Pruefung hier hat einen Abschnitt in docs/konventionen.md. Wer eine Norm aendert,
aendert beides.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

WURZEL = Path(__file__).resolve().parent.parent

AUS = {".git", "target", "saves", "assets/extern", ".cargo", "__pycache__",
       "tools/__pycache__"}


def ist_ausgeschlossen(p: Path) -> bool:
    rel = p.relative_to(WURZEL).as_posix()
    teile = set(rel.split("/"))
    return any(rel == a or rel.startswith(a + "/") or a in teile for a in AUS)


def ist_generiert(text: str) -> bool:
    """Erzeugte Dateien tragen ihren Erzeuger im Kopf und werden nicht gepflegt."""
    return "GENERIERT von tools/" in text[:400]


def dateien(*muster: str) -> list[Path]:
    treffer: list[Path] = []
    for m in muster:
        treffer += [p for p in WURZEL.glob(m) if p.is_file() and not ist_ausgeschlossen(p)]
    return sorted(set(treffer))


class Bericht:
    def __init__(self) -> None:
        self.fehler: list[str] = []
        self.geprueft = 0

    def pruefe(self, bedingung: bool, meldung: str) -> None:
        self.geprueft += 1
        if not bedingung:
            self.fehler.append(meldung)

    def melde(self, meldung: str) -> None:
        self.fehler.append(meldung)


# --------------------------------------------------------------------------
# 1. Commit-Message
# --------------------------------------------------------------------------

BETREFF = re.compile(
    r"^(?:(?:F|T)-\d{3}[a-z]?(?: [a-z]+)?|docs|test|tool|fix|chore): \S.*$")
SPUREN = re.compile(r"co-authored-by|generated with|generated by|\bclaude\b|\bai\b|🤖",
                    re.IGNORECASE)


def pruefe_commit_message(text: str, b: Bericht) -> None:
    zeilen = text.strip().splitlines()
    if not zeilen:
        b.melde("Commit-Message ist leer")
        return
    betreff = zeilen[0]

    b.pruefe(len(betreff) <= 72,
             f"Betreff ist {len(betreff)} Zeichen lang, erlaubt sind 72: {betreff!r}")
    b.pruefe(BETREFF.match(betreff) is not None,
             f"Betreff passt nicht auf '<F-ID|T-ID|docs|test|tool|fix|chore>: <text>': "
             f"{betreff!r}")
    b.pruefe(not betreff.endswith("."), f"Betreff endet mit einem Punkt: {betreff!r}")
    b.pruefe(not re.search(r"[\U0001F300-\U0001FAFF☀-➿]", betreff),
             f"Emoji im Betreff (die Stufen-Marken gehoeren in den Rumpf): {betreff!r}")

    # Keine Werkzeug- oder Autorenspuren — im GANZEN Text, nicht nur im Betreff (§10)
    for nr, z in enumerate(zeilen, 1):
        if SPUREN.search(z):
            b.melde(f"Werkzeug-/Autorenspur in Zeile {nr}: {z!r} — eine Commit-Message "
                    f"beschreibt die Aenderung, nicht ihren Urheber")
    if len(zeilen) > 1:
        b.pruefe(zeilen[1].strip() == "",
                 "Zwischen Betreff und Rumpf gehoert eine Leerzeile")


# --------------------------------------------------------------------------
# 2. Begriffe: kein Referenzbegriff im Code
# --------------------------------------------------------------------------

# Blatt 10_Namensschema ist verbindlich. Was hier steht, ist ein Fehler, den ein grep
# finden muss (prompts/init.md §2).
VERBOTEN = {
    r"\bnape\b": "Cortex",
    r"\bnacken\b": "Cortex",
    r"\bodm\b": "Vector Gear / vector",
    r"\b3dmg\b": "Vector Gear / vector",
    r"\bscouts?\b": "Vanguard",
    r"\bthunder[_ ]?spear\b": "Lance Charge",
    r"\bshifter\b": "Vessel Form",
    r"\btitan[_ ]shifting\b": "Bonding",
    r"\bperk\b": "Trait",
    r"\bartifact\b": "Relic",
    r"\bprestige\b": "Ascension",
    r"\bgems?\b": "Sigil",
    r"\bstuds?\b": "Meter (1 stud = 0,28 m, Umrechnung bei der Uebernahme in die RON)",
    r"\bpure[_ ]titan\b": "Husk",
    r"\babnormal\b": "Errant",
    r"\bcrawler\b": "Scuttler",
    r"\bducker\b": "Weaver",
}

# Dateien, die die Zuordnung ERKLAEREN und die Begriffe deshalb enthalten muessen.
BEGRIFFS_AUSNAHMEN = {
    "tools/normen.py",
    "tools/features.py",   # bildet die SPALTENNAMEN der .xlsx ab (groesse_studs)
    "docs/konventionen.md",
    "docs/architektur.md",
    "docs/backlog/namensschema.ron",
    "docs/backlog/funktionen.ron",
    "docs/backlog/tech.ron",
    "docs/backlog/maps.ron",
    "docs/backlog/modelle.ron",
    "docs/backlog/animationen.ron",
    "docs/backlog/audio.ron",
    "docs/backlog/ui.ron",
    "docs/backlog/vfx.ron",
    "docs/backlog/texturen.ron",
    "docs/features.ron",
    "docs/FUNDE.md",
    "docs/FRAGEN.md",
    "docs/ROADMAP.md",
    "docs/multiplayer.md",
}


def pruefe_begriffe(b: Bericht) -> None:
    for p in dateien("src/**/*.rs", "assets/data/**/*.ron", "tools/**/*.py",
                     "tools/**/*.sh", "scripts/**/*.txt"):
        rel = p.relative_to(WURZEL).as_posix()
        if rel in BEGRIFFS_AUSNAHMEN:
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        kommentar = "//" if p.suffix in (".rs", ".ron") else "#"
        for nr, zeile in enumerate(text.splitlines(), 1):
            # Kommentare duerfen den Referenzbegriff NENNEN — genau dort steht ja, warum
            # er hier nicht mehr vorkommt und wie umgerechnet wird. Verboten ist er im
            # Code und in den Daten, nicht in der Begruendung.
            code = zeile.split(kommentar)[0]
            for muster, statt in VERBOTEN.items():
                if re.search(muster, code, re.IGNORECASE):
                    b.melde(f"{rel}:{nr} Referenzbegriff {muster} — richtig waere: {statt}")
        b.geprueft += 1


# --------------------------------------------------------------------------
# 3. Code-Regeln, die still verfallen wuerden
# --------------------------------------------------------------------------

def pruefe_code(b: Bericht) -> None:
    for p in dateien("src/**/*.rs"):
        rel = p.relative_to(WURZEL).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        for nr, zeile in enumerate(text.splitlines(), 1):
            nackt = zeile.split("//")[0]
            if "unsafe" in nackt:
                b.melde(f"{rel}:{nr} `unsafe` ist verboten — nach docs/FRAGEN.md damit (§9d)")
            if "TEMP" in zeile:
                b.melde(f"{rel}:{nr} vergessener `// TEMP`-Hack (§15)")
            # Kein Dateiname im Code: die Registratur entscheidet, welches Asset benutzt
            # wird — es gibt EINE Stelle, die sie liest, und das ist src/data/ (§7).
            if not rel.startswith("src/data/"):
                if re.search(r'\.load\(\s*"', nackt):
                    b.melde(f"{rel}:{nr} Dateiname im Code — der Code fragt nach dem "
                            f"logischen Namen, die Registratur entscheidet (§7)")
                if re.search(r'\b(assets|\.glb|\.ogg|\.png)"', nackt):
                    b.melde(f"{rel}:{nr} Asset-Pfad im Code — gehoert in "
                            f"assets/data/art.ron (§7)")
            # §6 Regel 3: es gibt keinen 'den Spieler'
            if re.search(r"\.single\(\)|\.single_mut\(\)", nackt) and "Spieler" in text:
                b.melde(f"{rel}:{nr} `.single()` in einer Datei, die Spieler kennt — "
                        f"jeder Spieler ist einer von vielen (§6 Regel 3)")
        b.geprueft += 1


# --------------------------------------------------------------------------
# 4. Doku: ISO-Datum, Kopfzeile, tote Links, Zombie-Dateien
# --------------------------------------------------------------------------

ISO = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
LINK = re.compile(r"\[[^\]]*\]\(([^)#][^)]*)\)")


def pruefe_doku(b: Bericht) -> None:
    for p in dateien("docs/**/*.md", "README.md", "CLAUDE.md"):
        rel = p.relative_to(WURZEL).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        zeilen = text.splitlines()
        if not zeilen:
            b.melde(f"{rel} ist leer")
            continue
        if rel not in ("README.md", "CLAUDE.md"):
            b.pruefe(zeilen[0].startswith("# ") or ist_generiert(text),
                     f"{rel}: erste Zeile ist keine Ueberschrift '# <name> — <ein Satz>'")
            # Erzeugte Ansichten tragen keinen Stand: ihr Stand ist der ihrer Quelle,
            # und ein Datum, das sich bei jedem Lauf aendert, ist Diff-Rauschen.
            if not ist_generiert(text):
                b.pruefe(any("Stand:" in z for z in zeilen[:6]),
                         f"{rel}: keine Zeile 'Stand: <ISO>' in den ersten sechs "
                         f"Zeilen (§10)")
        for nr, z in enumerate(zeilen, 1):
            if z.strip().startswith("Stand:"):
                b.pruefe(ISO.search(z) is not None,
                         f"{rel}:{nr} Stand ohne ISO-Datum: {z.strip()!r}")
        # tote Links
        for ziel in LINK.findall(text):
            if ziel.startswith(("http://", "https://", "mailto:")):
                continue
            pfad = (p.parent / ziel.split("#")[0]).resolve()
            if not pfad.exists():
                b.melde(f"{rel}: toter Link auf {ziel} (§10 — ein Link ins Leere ist ein Bug)")
        b.geprueft += 1


def pruefe_zombies(b: Bericht) -> None:
    """Jede Datei ist verlinkt/benutzt — oder geloescht. Dazwischen gibt es nichts."""
    alle_texte = []
    for p in dateien("**/*.md", "**/*.rs", "**/*.ron", "**/*.py", "**/*.sh", "**/*.toml",
                     "**/*.txt"):
        alle_texte.append((p, p.read_text(encoding="utf-8", errors="replace")))

    for p in dateien("docs/**/*", "assets/**/*", "tools/**/*", "scripts/**/*"):
        rel = p.relative_to(WURZEL).as_posix()
        name = p.name
        erwaehnt = any(
            (rel in text or name in text) for q, text in alle_texte if q != p)
        if not erwaehnt:
            b.melde(f"{rel} wird nirgends erwaehnt — verlinken oder loeschen (§10). "
                    f"Eine Datei, die niemand kennt, sieht wie Wahrheit aus und wird nie "
                    f"gepflegt")
        b.geprueft += 1


# --------------------------------------------------------------------------
# 5. Testnamen und Screenshot-Namen
# --------------------------------------------------------------------------

def pruefe_tests(b: Bericht) -> None:
    fid = re.compile(r"^\s*fn\s+([a-z0-9_]+)\s*\(")
    for p in dateien("tests/**/*.rs"):
        rel = p.relative_to(WURZEL).as_posix()
        text = p.read_text(encoding="utf-8", errors="replace")
        zeilen = text.splitlines()
        for nr, z in enumerate(zeilen):
            if "#[test]" not in z:
                continue
            for folge in zeilen[nr + 1:nr + 4]:
                m = fid.match(folge)
                if not m:
                    continue
                name = m.group(1)
                # Ein Testname sagt die AUSSAGE, die gilt — nicht 'test_gas'.
                if name.startswith("test_"):
                    b.melde(f"{rel}: Test heisst {name!r} — der Name ist die Aussage, "
                            f"die gilt (z. B. f014_boost_verbraucht_gas), nicht 'test_x'")
                if re.match(r"^[ft]\d{3}", name) and "_" not in name:
                    b.melde(f"{rel}: Test {name!r} hat eine ID, aber keine Aussage")
                break
        b.geprueft += 1

    for p in dateien("docs/bilder/*"):
        rel = p.relative_to(WURZEL).as_posix()
        if p.suffix.lower() != ".png":
            continue
        if not re.match(r"^[ftb]-?\d{3}[a-z]?-[a-z0-9-]+(-vorher|-nachher)?\.png$", p.name):
            b.melde(f"{rel}: Screenshot-Name passt nicht auf "
                    f"<f-id>-<kurz>[-vorher|-nachher].png (§10)")
        b.geprueft += 1


# --------------------------------------------------------------------------

def main() -> int:
    b = Bericht()

    if "--commit-msg" in sys.argv:
        i = sys.argv.index("--commit-msg")
        pfad = Path(sys.argv[i + 1])
        pruefe_commit_message(
            pfad.read_text(encoding="utf-8").split("# ------------------------ >8")[0], b)
    else:
        pruefe_begriffe(b)
        pruefe_code(b)
        pruefe_doku(b)
        pruefe_zombies(b)
        pruefe_tests(b)

    if b.fehler:
        print(f"NORMEN: {len(b.fehler)} Verstoss/Verstoesse "
              f"({b.geprueft} Pruefungen):", file=sys.stderr)
        for f in b.fehler:
            print("  - " + f, file=sys.stderr)
        return 1
    print(f"NORMEN: in Ordnung ({b.geprueft} Pruefungen)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
